# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57354f76f7918fbf74d6feadd75b3c6552bf5d844b17c3bf114c01e27185aead25abead75cc17503e550df8885d9848b7bc4613e692f0e48bca94a81a0fe3e24

test:
  secret_key_base: 759d52aeb073a66d4b2d584f1b4f1c6af84b304ec9667f6f01f0225aed0f01d5938a7a26e5d2baa8f90b385fd3d2339fd2edd0bb0e37b185d8fbb940c0849165

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
